gem     "rerun"
gem     "thin"
gem     "chronic", "=0.2.3"
gem     "sinatra", "=1.0"
gem     "haml", "=2.2.21"
gem     "rack-flash", "=0.1.1"
gem     "yajl-ruby", "=0.7.5"
gem     "sinatra-respond_to", "=0.4.0"
gem     "sinatra-outputbuffer", "=0.1.0"
gem     "chronic", "=0.2.3"
gem     "memcached"